### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by Neur1n** [iamcco/coc-diagnostic#19]
(Continuing from #18.)

### Test File
An empty `test.html` file.

### Test Procedure
Typing `<dic` into the test HTML file.

#### Before typing in anything
Output of `:CocInfo`:
```
## versions

vim version: NVIM v0.5.0-357-g405f49a9b
node version: v12.13.0
coc.nvim version: 0.0.74-6700e7468d
term: undefined
platform: win32

## Messages

## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in c:\Users\***\Desktop
fatal: not a git repository (or any of the parent directories): .git

## Output channel: snippets
```
Output of `:CocOpenLog`:
```
2020-02-09T23:45:13.035 INFO (pid:4272) [services] - registered service "languageserver.clangd"
2020-02-09T23:45:13.100 INFO (pid:4272) [services] - registered service "html"
2020-02-09T23:45:13.100 INFO (pid:4272) [services] - HTML language server state change: stopped => starting
2020-02-09T23:45:13.110 INFO (pid:4272) [services] - registered service "diagnostic-languageserver"
2020-02-09T23:45:13.110 INFO (pid:4272) [services] - diagnostic language service state change: stopped => starting
2020-02-09T23:45:13.183 INFO (pid:4272) [language-client-index] - html started with 7368
2020-02-09T23:45:13.205 INFO (pid:4272) [language-client-index] - diagnostic-languageserver started with 12764
2020-02-09T23:45:13.268 INFO (pid:4272) [plugin] - coc 0.0.74-6700e7468d initialized with node: v12.13.0
2020-02-09T23:45:13.291 INFO (pid:4272) [language-client-index] - cSpell started with 3712
2020-02-09T23:45:13.304 INFO (pid:4272) [services] - diagnostic language service state change: starting => running
2020-02-09T23:45:13.307 INFO (pid:4272) [services] - service diagnostic-languageserver started
2020-02-09T23:45:13.499 INFO (pid:4272) [services] - HTML language server state change: starting => running
2020-02-09T23:45:13.501 INFO (pid:4272) [services] - service html started
```

#### After editing and saving
Output of `:CocInfo` is not changed.
Output of `:CocOpenLog` is changed:
```
2020-02-09T23:45:13.035 INFO (pid:4272) [services] - registered service "languageserver.clangd"
2020-02-09T23:45:13.100 INFO (pid:4272) [services] - registered service "html"
2020-02-09T23:45:13.100 INFO (pid:4272) [services] - HTML language server state change: stopped => starting
2020-02-09T23:45:13.110 INFO (pid:4272) [services] - registered service "diagnostic-languageserver"
2020-02-09T23:45:13.110 INFO (pid:4272) [services] - diagnostic language service state change: stopped => starting
2020-02-09T23:45:13.183 INFO (pid:4272) [language-client-index] - html started with 7368
2020-02-09T23:45:13.205 INFO (pid:4272) [language-client-index] - diagnostic-languageserver started with 12764
2020-02-09T23:45:13.268 INFO (pid:4272) [plugin] - coc 0.0.74-6700e7468d initialized with node: v12.13.0
2020-02-09T23:45:13.291 INFO (pid:4272) [language-client-index] - cSpell started with 3712
2020-02-09T23:45:13.304 INFO (pid:4272) [services] - diagnostic language service state change: starting => running
2020-02-09T23:45:13.307 INFO (pid:4272) [services] - service diagnostic-languageserver started
2020-02-09T23:45:13.499 INFO (pid:4272) [services] - HTML language server state change: starting => running
2020-02-09T23:45:13.501 INFO (pid:4272) [services] - service html started
2020-02-09T23:47:39.244 INFO (pid:4272) [completion-complete] - Results from: html
2020-02-09T23:47:51.394 INFO (pid:4272) [willSaveHandler] - Will save cost: 1
```

Additionally, while testing on the Ubuntu 16.04 machine:
#### Before typing in anything
At this moment, the file is still empty but the gutter shows a warning symbol, and with 1 warning showing in `:CocList diagnostics`. The output of `:CocOpenLog`
```
2020-02-09T23:51:23.049 INFO (pid:12140) [services] - registered service "languageserver.clangd"
2020-02-09T23:51:23.068 INFO (pid:12140) [services] - registered service "diagnostic-languageserver"
2020-02-09T23:51:23.068 INFO (pid:12140) [services] - diagnostic language service state change: stopped => starting
2020-02-09T23:51:23.100 INFO (pid:12140) [services] - registered service "html"
2020-02-09T23:51:23.100 INFO (pid:12140) [services] - HTML language server state change: stopped => starting
2020-02-09T23:51:23.172 INFO (pid:12140) [language-client-index] - diagnostic-languageserver started with 12154
2020-02-09T23:51:23.179 INFO (pid:12140) [language-client-index] - html started with 12160
2020-02-09T23:51:23.209 INFO (pid:12140) [plugin] - coc 0.0.74-6700e7468d initialized with node: v12.13.0
2020-02-09T23:51:23.213 INFO (pid:12140) [language-client-index] - cSpell started with 12171
2020-02-09T23:51:23.248 INFO (pid:12140) [services] - diagnostic language service state change: starting => running
2020-02-09T23:51:23.250 INFO (pid:12140) [services] - service diagnostic-languageserver started
2020-02-09T23:51:23.442 INFO (pid:12140) [services] - HTML language server state change: starting => running
2020-02-09T23:51:23.445 INFO (pid:12140) [services] - service html started
```

#### After editing and saving
At this moment, the gutter shows an error symbol, and with 1 error and 4 warnings showing in `:CocList diagnostics`.
Output of `:CocOpenLog` is changed:
```
2020-02-09T23:51:23.049 INFO (pid:12140) [services] - registered service "languageserver.clangd"
2020-02-09T23:51:23.068 INFO (pid:12140) [services] - registered service "diagnostic-languageserver"
2020-02-09T23:51:23.068 INFO (pid:12140) [services] - diagnostic language service state change: stopped => starting
2020-02-09T23:51:23.100 INFO (pid:12140) [services] - registered service "html"
2020-02-09T23:51:23.100 INFO (pid:12140) [services] - HTML language server state change: stopped => starting
2020-02-09T23:51:23.172 INFO (pid:12140) [language-client-index] - diagnostic-languageserver started with 12154
2020-02-09T23:51:23.179 INFO (pid:12140) [language-client-index] - html started with 12160
2020-02-09T23:51:23.209 INFO (pid:12140) [plugin] - coc 0.0.74-6700e7468d initialized with node: v12.13.0
2020-02-09T23:51:23.213 INFO (pid:12140) [language-client-index] - cSpell started with 12171
2020-02-09T23:51:23.248 INFO (pid:12140) [services] - diagnostic language service state change: starting => running
2020-02-09T23:51:23.250 INFO (pid:12140) [services] - service diagnostic-languageserver started
2020-02-09T23:51:23.442 INFO (pid:12140) [services] - HTML language server state change: starting => running
2020-02-09T23:51:23.445 INFO (pid:12140) [services] - service html started
2020-02-09T23:55:17.143 INFO (pid:12140) [completion-complete] - Results from: html
2020-02-09T23:59:02.262 INFO (pid:12140) [willSaveHandler] - Will save cost: 4
```

**Comment by iamcco** [comment]
update and have a try.

**Comment by Neur1n** [comment]
Still not working ...

**Comment by iamcco** [comment]
add `  "diagnostic-languageserver.trace.server": "verbose"` to coc-settings.json and checkout output channel.

`:CocList output` then select `diagnostic-languageserver`

**Comment by Neur1n** [comment]
### Before input anything
(The huge `Params` section is omitted, and the user name is replaced with "***".)
```
[Trace - 7:04:26 PM] Sending request 'initialize - (0)'.

[Trace - 7:04:26 PM] Received response 'initialize - (0)' in 97ms.
Result: {
    "capabilities": {
        "textDocumentSync": 1,
        "documentFormattingProvider": true
    }
}


[Trace - 7:04:26 PM] Sending notification 'initialized'.
Params: {}


[Trace - 7:04:26 PM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/***/Desktop/test.html",
        "languageId": "html",
        "version": 1,
        "text": "\n"
    }
}


[Trace - 7:04:26 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///c%3A/Users/***/Desktop/test.html",
    "diagnostics": []
}
```

### After typing in "<dic" and saved
**Additional** logs are shown:
```
[Trace - 7:05:42 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/***/Desktop/test.html",
        "version": 2
    },
    "contentChanges": [
        {
            "text": "<\n"
        }
    ]
}


[Trace - 7:05:42 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///c%3A/Users/***/Desktop/test.html",
    "diagnostics": []
}


[Trace - 7:05:44 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/***/Desktop/test.html",
        "version": 3
    },
    "contentChanges": [
        {
            "text": "<dic\n"
        }
    ]
}


[Trace - 7:05:44 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///c%3A/Users/***/Desktop/test.html",
    "diagnostics": []
}


[Trace - 7:05:45 PM] Sending notification 'textDocument/didSave'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/***/Desktop/test.html",
        "version": 3
    }
}


[Trace - 7:05:45 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///c%3A/Users/***/Desktop/test.html",
    "diagnostics": []
}
```

**Comment by iamcco** [comment]
Still can not see any error log. Need test on windows when have time.

**Comment by Neur1n** [comment]
Your effort is much appreciated. Is the diagnostic information handled by coc itself? Because I don't see any related code in this plugin when I tried to debug (or I just didn't understand the code).

**Comment by yaegassy** [comment]
I think "rootPatterns" is `[".git/"]`, setting.

https://github.com/iamcco/coc-diagnostic/issues/18#issuecomment-583752792

I can check the contents of `"uri": "file:///c%3A/Users/***/Desktop/test.html"`, but is there `Desktop/.git`?

How about creating `test.html` and `.git/` (git init) in a different directory and trying it out?

**Comment by Neur1n** [comment]
Here is the test result:

1. Put the `test.html` file into a git repo, not working.
2. Set the "rootPatterns" to `["./"]`, not working. (Or [`"\\./"`]? I'm not sure.)
3. Remove the "rootPatterns" setting, not working.

**Comment by iamcco** [comment]
@Neur1n  Diagnostic information is handled by https://github.com/iamcco/diagnostic-languageserver

**Comment by Neur1n** [comment]
Where is the `diagnostic-languageserver` installed actually? I couldn't find the `handleLinter` function as you mentioned, and I couldn't find the yarn package named "diagnostic-languageserver" (neither in the Ubuntu machine on which coc-diagnosic is working properly).

Then I found I didn't install yarn on my Windows machine, so I install it. But:
1. At first, not working
2. I install `diagnostic-languageserver` manually with `yarn global add diagnostic-languageserver`, not working

**Comment by iamcco** [comment]
@Neur1n It will not install `diagnostic-languageserver` since it's bundle with the extension

https://github.com/iamcco/coc-diagnostic/blob/master/src/server.ts

You can disable this extension and register `diagnostic-languageserver` in coc-settings.json to debug.

**Comment by Neur1n** [comment]
So when I do as what you said, the following messages are echoed when I opened the empty `test.html`:
![image](https://user-images.githubusercontent.com/17579247/74206713-8017f000-4cb7-11ea-80da-1e9d856e5bb5.png)

And I tried to run `diagnostic-languageserver` in terminal:
```powershell
C:\Users\***\AppData\Local\Yarn\Data\global\node_modules\vscode-languageserver\lib\main.js:799
        throw new Error("Connection input stream is not set. " + commandLineMessage);
        ^

Error: Connection input stream is not set. Use arguments of createConnection or set command line parameters: '--node-ipc', '--stdio' or '--socket={number}'
    at _createConnection (C:\Users\***\AppData\Local\Yarn\Data\global\node_modules\[4mvscode-languageserver[24m\lib\main.js:799:15)
    at Object.createConnection (C:\Users\***\AppData\Local\Yarn\Data\global\node_modules\[4mvscode-languageserver[24m\lib\main.js:746:12)
    at Object.<anonymous> (C:\Users\***\AppData\Local\Yarn\Data\global\node_modules\[4mdiagnostic-languageserver[24m\lib\index.js:10:42)
[90m    at Module._compile (internal/modules/cjs/loader.js:956:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:812:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:724:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:849:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:74:18)[39m
    at Object.<anonymous> (C:\Users\***\AppData\Local\Yarn\Data\global\node_modules\[4mdiagnostic-languageserver[24m\bin\index.js:3:1)
```

**Comment by iamcco** [comment]
> ![](https://user-images.githubusercontent.com/17579247/74206713-8017f000-4cb7-11ea-80da-1e9d856e5bb5.png)

What's your settings for those error?

You have to specify `--stdio` when run in terminal `diagnostic-languageserver --stdio`

**Comment by Neur1n** [comment]
Yea, you are right. After specifying `--stdio`, not errors thrown.
Previously, my settings are:
```json
  "dls": {
        "command": "diagnostic-languageserver",
        "args": ["--stdio"],
        "filetypes": [ "html", "vim" ],
        "initializationOptions": {
          "linters": {
            "tidy": {
              "command": "tidy",
              "args": ["-e", "-q"],
              "isStderr": "true",
              "debounce": 100,
              "offsetLine": 0,
              "offsetColumn": 0,
              "sourceName": "tidy",
              "formatLines": 1,
              "formatPattern": [
                "^.*?(\\d+).*?(\\d+)\\s+-\\s+([^:]+):\\s+(.*)$",
                {
                  "line": 1,
                  "column": 2,
                  "endLine": 1,
                  "endColumn": 2,
                  "message": [4],
                  "security": 3
                }
              ],
              "securities": {
                "Error": "error",
                "Warning": "warning"
              }
            }
          },
          "filetypes": {
            "html": "tidy",
            "vim": "vint"
          },
        }
      }
```
Then I change `"command": "diagnostic-languageserver"` to `"command": "diagnostic-languageserver.cmd"`, now the error messages are gone. But still there are no diagnostic information show up.

**Comment by iamcco** [comment]
I have add more log, please update this extensions and set `"diagnostic-languageserver.trace.server": "verbose"` then checkout output channel of coc-diagnostic.

**Comment by Neur1n** [comment]
Based on the output of `:CocList output` (and select "diagnostic-languageserver"), it seems that the errors of the test file is caught by the linter. Please check the following details.

NOTE:
1. The `rootPatterns` is left as default.
2. Based on the log, I tried to set `isStderr` or `isStdout` to be `true`/`false` (I mean all combinations), but no luck.

### Before typing in anythin
```
[Trace - 1:37:10 PM] Received response 'initialize - (0)' in 108ms.
Result: {
    "capabilities": {
        "textDocumentSync": 1,
        "documentFormattingProvider": true
    }
}


[Trace - 1:37:10 PM] Sending notification 'initialized'.
Params: {}


[Trace - 1:37:10 PM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/***/Desktop/test.html",
        "languageId": "html",
        "version": 1,
        "text": "\n"
    }
}


[Trace - 1:37:11 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "Linter command: tidy, args: [\"-e\",\"-q\"]"
}


Linter command: tidy, args: ["-e","-q"]
[Trace - 1:37:11 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "stdout: "
}


stdout: 
[Trace - 1:37:11 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "stderr: line 2 column 1 - Warning: inserting missing 'title' element\r\r\n"
}


stderr: line 2 column 1 - Warning: inserting missing 'title' element


[Trace - 1:37:11 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match string: line 2 column 1 - Warning: inserting missing 'title' element\r\r"
}


match string: line 2 column 1 - Warning: inserting missing 'title' element

[Trace - 1:37:11 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match result: null"
}


match result: null
[Trace - 1:37:11 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match string: "
}


match string: 
[Trace - 1:37:11 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match result: null"
}


match result: null
[Trace - 1:37:11 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///c%3A/Users/***/Desktop/test.html",
    "diagnostics": []
}
```

### After typing in "<dic" and saved
The **additional** log:
```
[Trace - 1:39:24 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/***/Desktop/test.html",
        "version": 2
    },
    "contentChanges": [
        {
            "text": "<\n"
        }
    ]
}


[Trace - 1:39:24 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "Linter command: tidy, args: [\"-e\",\"-q\"]"
}


Linter command: tidy, args: ["-e","-q"]
[Trace - 1:39:24 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "stdout: "
}


stdout: 
[Trace - 1:39:24 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "stderr: line 1 column 1 - Warning: missing <!DOCTYPE> declaration\r\r\nline 1 column 1 - Warning: plain text isn't allowed in <head> elements\r\r\nline 1 column 1 - Info: <head> previously mentioned\r\r\nline 1 column 1 - Warning: inserting implicit <body>\r\r\nline 1 column 1 - Warning: inserting missing 'title' element\r\r\n"
}


stderr: line 1 column 1 - Warning: missing <!DOCTYPE> declaration

line 1 column 1 - Warning: plain text isn't allowed in <head> elements

line 1 column 1 - Info: <head> previously mentioned

line 1 column 1 - Warning: inserting implicit <body>

line 1 column 1 - Warning: inserting missing 'title' element


[Trace - 1:39:24 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match string: line 1 column 1 - Warning: missing <!DOCTYPE> declaration\r\r"
}


match string: line 1 column 1 - Warning: missing <!DOCTYPE> declaration

[Trace - 1:39:24 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match result: null"
}


match result: null
[Trace - 1:39:24 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match string: line 1 column 1 - Warning: plain text isn't allowed in <head> elements\r\r"
}


match string: line 1 column 1 - Warning: plain text isn't allowed in <head> elements

[Trace - 1:39:24 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match result: null"
}


match result: null
[Trace - 1:39:24 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match string: line 1 column 1 - Info: <head> previously mentioned\r\r"
}


match string: line 1 column 1 - Info: <head> previously mentioned

[Trace - 1:39:24 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match result: null"
}


match result: null
[Trace - 1:39:24 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match string: line 1 column 1 - Warning: inserting implicit <body>\r\r"
}


match string: line 1 column 1 - Warning: inserting implicit <body>

[Trace - 1:39:24 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match result: null"
}


match result: null
[Trace - 1:39:24 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match string: line 1 column 1 - Warning: inserting missing 'title' element\r\r"
}


match string: line 1 column 1 - Warning: inserting missing 'title' element

[Trace - 1:39:24 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match result: null"
}


match result: null
[Trace - 1:39:24 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match string: "
}


match string: 
[Trace - 1:39:24 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match result: null"
}


match result: null
[Trace - 1:39:24 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///c%3A/Users/***/Desktop/test.html",
    "diagnostics": []
}


[Trace - 1:39:24 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/***/Desktop/test.html",
        "version": 3
    },
    "contentChanges": [
        {
            "text": "<dic\n"
        }
    ]
}


[Trace - 1:39:25 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "Linter command: tidy, args: [\"-e\",\"-q\"]"
}


Linter command: tidy, args: ["-e","-q"]
[Trace - 1:39:25 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "stdout: "
}


stdout: 
[Trace - 1:39:25 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "stderr: line 2 column 1 - Warning: <dic> end of file while parsing attributes\r\r\nline 1 column 1 - Error: <dic> is not recognized!\r\r\nline 2 column 1 - Warning: missing <!DOCTYPE> declaration\r\r\nline 1 column 1 - Warning: discarding unexpected <dic>\r\r\nline 2 column 1 - Warning: inserting missing 'title' element\r\r\n"
}


stderr: line 2 column 1 - Warning: <dic> end of file while parsing attributes

line 1 column 1 - Error: <dic> is not recognized!

line 2 column 1 - Warning: missing <!DOCTYPE> declaration

line 1 column 1 - Warning: discarding unexpected <dic>

line 2 column 1 - Warning: inserting missing 'title' element


[Trace - 1:39:25 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match string: line 2 column 1 - Warning: <dic> end of file while parsing attributes\r\r"
}


match string: line 2 column 1 - Warning: <dic> end of file while parsing attributes

[Trace - 1:39:25 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match result: null"
}


match result: null
[Trace - 1:39:25 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match string: line 1 column 1 - Error: <dic> is not recognized!\r\r"
}


match string: line 1 column 1 - Error: <dic> is not recognized!

[Trace - 1:39:25 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match result: null"
}


match result: null
[Trace - 1:39:25 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match string: line 2 column 1 - Warning: missing <!DOCTYPE> declaration\r\r"
}


match string: line 2 column 1 - Warning: missing <!DOCTYPE> declaration

[Trace - 1:39:25 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match result: null"
}


match result: null
[Trace - 1:39:25 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match string: line 1 column 1 - Warning: discarding unexpected <dic>\r\r"
}


match string: line 1 column 1 - Warning: discarding unexpected <dic>

[Trace - 1:39:25 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match result: null"
}


match result: null
[Trace - 1:39:25 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match string: line 2 column 1 - Warning: inserting missing 'title' element\r\r"
}


match string: line 2 column 1 - Warning: inserting missing 'title' element

[Trace - 1:39:25 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match result: null"
}


match result: null
[Trace - 1:39:25 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match string: "
}


match string: 
[Trace - 1:39:25 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match result: null"
}


match result: null
[Trace - 1:39:25 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///c%3A/Users/***/Desktop/test.html",
    "diagnostics": []
}


[Trace - 1:39:28 PM] Sending notification 'textDocument/didSave'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/***/Desktop/test.html",
        "version": 3
    }
}


[Trace - 1:39:28 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "Linter command: tidy, args: [\"-e\",\"-q\"]"
}


Linter command: tidy, args: ["-e","-q"]
[Trace - 1:39:28 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "stdout: "
}


stdout: 
[Trace - 1:39:28 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "stderr: line 2 column 1 - Warning: <dic> end of file while parsing attributes\r\r\nline 1 column 1 - Error: <dic> is not recognized!\r\r\nline 2 column 1 - Warning: missing <!DOCTYPE> declaration\r\r\nline 1 column 1 - Warning: discarding unexpected <dic>\r\r\nline 2 column 1 - Warning: inserting missing 'title' element\r\r\n"
}


stderr: line 2 column 1 - Warning: <dic> end of file while parsing attributes

line 1 column 1 - Error: <dic> is not recognized!

line 2 column 1 - Warning: missing <!DOCTYPE> declaration

line 1 column 1 - Warning: discarding unexpected <dic>

line 2 column 1 - Warning: inserting missing 'title' element


[Trace - 1:39:28 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match string: line 2 column 1 - Warning: <dic> end of file while parsing attributes\r\r"
}


match string: line 2 column 1 - Warning: <dic> end of file while parsing attributes

[Trace - 1:39:28 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match result: null"
}


match result: null
[Trace - 1:39:28 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match string: line 1 column 1 - Error: <dic> is not recognized!\r\r"
}


match string: line 1 column 1 - Error: <dic> is not recognized!

[Trace - 1:39:28 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match result: null"
}


match result: null
[Trace - 1:39:28 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match string: line 2 column 1 - Warning: missing <!DOCTYPE> declaration\r\r"
}


match string: line 2 column 1 - Warning: missing <!DOCTYPE> declaration

[Trace - 1:39:28 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match result: null"
}


match result: null
[Trace - 1:39:28 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match string: line 1 column 1 - Warning: discarding unexpected <dic>\r\r"
}


match string: line 1 column 1 - Warning: discarding unexpected <dic>

[Trace - 1:39:28 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match result: null"
}


match result: null
[Trace - 1:39:28 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match string: line 2 column 1 - Warning: inserting missing 'title' element\r\r"
}


match string: line 2 column 1 - Warning: inserting missing 'title' element

[Trace - 1:39:28 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match result: null"
}


match result: null
[Trace - 1:39:28 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match string: "
}


match string: 
[Trace - 1:39:28 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "match result: null"
}


match result: null
[Trace - 1:39:28 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///c%3A/Users/***/Desktop/test.html",
    "diagnostics": []
}
```

**Comment by Neur1n** [comment]
FINALLY! I just noticed the `\r\r` in the logs, so I removed the "$" from the `formatPattern`, and it works!

**Comment by iamcco** [comment]
Seems only have `\r\r` on windows. Closed since it's not an issue of extension.

**Comment by Neur1n** [comment]
After some tests, adding `\\s` before `$` also works. But I'm not sure the proper way to make it compatible among Windows and Linux/Unix. Would you please provide some advice?

And maybe the default configurations of linters (e.g. vint) can be update as well?

Anyway, thanks a lot. Your help is much appreciated.

**Comment by iamcco** [comment]
Using `(\\r|\\n)*$` to cover this case "^.*?(\\d+).*?(\\d+)\\s+-\\s+([^:]+):\\s+(.*)(\\r|\\n)*$"`

**Comment by iamcco** [comment]
I have update a new version with new default config.
