### ISSUE TITLE
Vint not working

### ISSUE THREAD

**Issue by jmolero** [iamcco/coc-diagnostic#21]
Vint shows some errors like "Not an editor command" but not other style errors I get when running the CLI command. 

I think it's because of this error on the `CocInfo`:

```
## versions

vim version: NVIM v0.4.3
node version: v10.18.1
coc.nvim version: 0.0.74-98a709ec3f
term: Apple_Terminal
platform: darwin

## Messages

## Output channel: diagnostic-languageserver

Linter command: vint, args: ["--enable-neovim","-"]
stdout: 
stderr: Traceback (most recent call last):
  File "/usr/local/bin/vint", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/vint/__init__.py", line 11, in main
    init_cli()
  File "/usr/local/lib/python3.7/site-packages/vint/bootstrap.py", line 22, in init_cli
    cli.start()
  File "/usr/local/lib/python3.7/site-packages/vint/linting/cli.py", line 27, in start
    violations = self._lint_all(env, config_dict)
  File "/usr/local/lib/python3.7/site-packages/vint/linting/cli.py", line 121, in _lint_all
    violations += linter.lint_text(sys.stdin.read())
  File "/usr/local/lib/python3.7/site-packages/vint/linting/linter.py", line 132, in lint_text
    self._traverse(root_ast, 'stdin')
  File "/usr/local/lib/python3.7/site-packages/vint/linting/linter.py", line 150, in _traverse
    on_leave=lambda node: self._handle_leave(node, lint_context))
  File "/usr/local/lib/python3.7/site-packages/vint/ast/traversing.py", line 234, in traverse
    should_traverse_children = on_enter(node) is not SKIP_CHILDREN
  File "/usr/local/lib/python3.7/site-packages/vint/linting/linter.py", line 149, in <lambda>
    on_enter=lambda node: self._handle_enter(node, lint_context),
  File "/usr/local/lib/python3.7/site-packages/vint/linting/linter.py", line 160, in _handle_enter
    self._fire_listeners(node, lint_context)
  File "/usr/local/lib/python3.7/site-packages/vint/linting/linter.py", line 178, in _fire_listeners
    violation = listening_policy.get_violation_if_found(node, lint_context)
  File "/usr/local/lib/python3.7/site-packages/vint/linting/policy/abstract_policy.py", line 38, in get_violation_if_found
    if self.is_valid(node, lint_context):
  File "/usr/local/lib/python3.7/site-packages/vint/linting/policy/prohibit_missing_scriptencoding.py", line 36, in is_valid
    return not self._check_script_has_multibyte_char(lint_context)
  File "/usr/local/lib/python3.7/site-packages/vint/linting/policy/prohibit_missing_scriptencoding.py", line 54, in _check_script_has_multibyte_char
    return self._check_stdin_has_multibyte_char()
  File "/usr/local/lib/python3.7/site-packages/vint/linting/policy/prohibit_missing_scriptencoding.py", line 64, in _check_stdin_has_multibyte_char
    sys.stdin.seek(0)
io.UnsupportedOperation: underlying stream is not seekable

match string: 
match result: null
```

My vint version is: `0.3.21`

**Comment by iamcco** [comment]
vint issue https://github.com/Vimjas/vint/issues/305

**Comment by iamcco** [comment]
But my vint v0.3.21 works well.

**Comment by jmolero** [comment]
Thank you!
