### ISSUE TITLE
Unable to capture output from gqlint

### ISSUE THREAD

**Issue by tkolleh** [iamcco/coc-diagnostic#36]
"Empty diagnostics" for GraphQL files when using gqlint. Why does coc-diagnostic not capture the below warnings from the linter?

<img width="804" alt="Screen Shot 2020-05-20 at 11 51 51 PM" src="https://user-images.githubusercontent.com/3095197/82521551-fddc6a80-9af4-11ea-8e61-67d4b4ac631c.png">

[(view provided regex)](https://regex101.com/r/74iROT/1)

##### Setup coc-settings.json file to lint GraphQL filetypes

```
  "diagnostic-languageserver.linters": {
    "gqlint": {
      "command": "gqlint",
      "debounce": 100,
      "offsetLine": 3,
      "offsetColumn": 1,
      "sourceName": "gqlint",
      "formatLines": 1,
      "formatPattern": [
        "^\\s+(\\d+):(\\d+)\\s+(\\w+)\\s+(\\w+)\\s+(.+)$",
        {
          "line": 1,
          "column": 2,
          "endLine": 1,
          "endColumn": 2,
          "message": 5,
          "security": 3
        }
      ],
      "securities": {
        "error": "error",
        "warning": "warning",
        "note": "info"
      }
    }
  },

  "diagnostic-languageserver.filetypes": {
    "graphql": "gqlint"
  },
  "diagnostic-languageserver.formatFiletypes": {
    "dart": "dartfmt"
  },
...
```

**Comment by iamcco** [comment]
Make sure the output is stdout or set below to use stderr output.

 ````
"isStdout": false, 
"isStderr": true
```

Also set `"diagnostic-languageserver.trace.server": "verbose"` and checkout output channel to see more log.

**Comment by tkolleh** [comment]
The Diagnostic list remains empty after adding the above settings.

<img width="831" alt="Screen Shot 2020-05-21 at 2 10 04 PM" src="https://user-images.githubusercontent.com/3095197/82591141-dde88d80-9b6c-11ea-98ee-3e48e298c69b.png">

> Items in red are stderr output


##### Errors

```
2020-05-21T13:52:14.022 WARN (pid:5499) [events] - Handler of InputChar blocked more than 2s: Error
    at Events.on (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:15338:25)
    at ListManager.init (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:60562:26)
....
2020-05-21T13:52:14.022 WARN (pid:5499) [events] - Handler of CursorMoved blocked more than 2s: Error
    at Events.on (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:15338:25)
    at Workspace.init (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:24302:26)
```

#### Logged output

```
2020-05-21T13:46:27.619 INFO (pid:5499) [services] - diagnostic language service state change: starting => running
2020-05-21T13:46:27.620 INFO (pid:5499) [services] - service diagnostic-languageserver started
2020-05-21T13:46:27.638 INFO (pid:5499) [services] - Json language server state change: starting => running
2020-05-21T13:46:27.640 INFO (pid:5499) [services] - service json started
2020-05-21T13:46:45.387 WARN (pid:5499) [events] - Handler of InputChar blocked more than 2s: Error
    at Events.on (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:15338:25)
    at ListManager.init (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:60562:26)
    at Plugin.init (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:22435:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async NeovimClient.<anonymous> (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:10365:21)
2020-05-21T13:46:45.388 WARN (pid:5499) [events] - Handler of CursorMoved blocked more than 2s: Error
    at Events.on (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:15338:25)
    at Workspace.init (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:24302:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Plugin.init (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:22430:13)
    at async NeovimClient.<anonymous> (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:10365:21)
2020-05-21T13:47:29.604 WARN (pid:5499) [events] - Handler of InputChar blocked more than 2s: Error
    at Events.on (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:15338:25)
    at ListManager.init (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:60562:26)
    at Plugin.init (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:22435:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async NeovimClient.<anonymous> (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:10365:21)
2020-05-21T13:47:29.606 WARN (pid:5499) [events] - Handler of CursorMoved blocked more than 2s: Error
    at Events.on (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:15338:25)
    at Workspace.init (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:24302:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Plugin.init (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:22430:13)
    at async NeovimClient.<anonymous> (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:10365:21)
2020-05-21T13:51:16.140 WARN (pid:5499) [events] - Handler of InputChar blocked more than 2s: Error
    at Events.on (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:15338:25)
    at ListManager.init (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:60562:26)
    at Plugin.init (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:22435:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async NeovimClient.<anonymous> (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:10365:21)
2020-05-21T13:51:16.142 WARN (pid:5499) [events] - Handler of CursorMoved blocked more than 2s: Error
    at Events.on (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:15338:25)
    at Workspace.init (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:24302:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Plugin.init (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:22430:13)
    at async NeovimClient.<anonymous> (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:10365:21)
2020-05-21T13:51:18.141 INFO (pid:5499) [services] - diagnostic language service state change: running => stopped
2020-05-21T13:51:18.147 INFO (pid:5499) [services] - registered service "diagnostic-languageserver"
2020-05-21T13:51:18.147 INFO (pid:5499) [services] - diagnostic language service state change: stopped => starting
2020-05-21T13:51:18.158 INFO (pid:5499) [language-client-index] - diagnostic-languageserver started with 7382
2020-05-21T13:51:18.260 INFO (pid:5499) [services] - diagnostic language service state change: starting => running
2020-05-21T13:51:18.261 INFO (pid:5499) [services] - service diagnostic-languageserver started
2020-05-21T13:52:14.022 WARN (pid:5499) [events] - Handler of InputChar blocked more than 2s: Error
    at Events.on (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:15338:25)
    at ListManager.init (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:60562:26)
    at Plugin.init (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:22435:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async NeovimClient.<anonymous> (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:10365:21)
2020-05-21T13:52:14.022 WARN (pid:5499) [events] - Handler of CursorMoved blocked more than 2s: Error
    at Events.on (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:15338:25)
    at Workspace.init (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:24302:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Plugin.init (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:22430:13)
    at async NeovimClient.<anonymous> (/Users/tkolleh/.local/share/plugged/coc.nvim/build/index.js:10365:21)
```

**Comment by iamcco** [comment]
I need the log of coc-diagnostic, check the output channel of coc-diagnostic

**Comment by iamcco** [comment]
https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by tkolleh** [comment]
Thank you for helping me resolve this issue. 

How are you determining if the output will be to *stdout* or *stderr*? 

I determine this using the `grep` command. E.g. `gqlint <pathtofile> | grep .` Items in red are *stderr*. 

The root cause of the issue was that gqlint linter was not properly configured, checking *stderr* but the logs stated that the output was coming through *stdout*. Which means either;

* the output is coming to *stdout* **->** grep command is incorrect
* the output is coming to *stderr* and the diagnostic-languageserver believes that it is *stdout* **->** diagnostic-languageserver is miss configured
* the output is coming to *stderr* and then passed to the diagnostic-languageserver as *stdout* **->** grep and diagnostic-languageserver (dls) are correct but dls is not differentiating between *stdout* and *stderr*

```
[Info  - 1:13:02 PM] found working directory /Users/tkolleh/**/dashboardapp
[Trace - 1:13:02 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "Linter command: gqlint, args: [\"%file\"]"
}

Linter command: gqlint, args: ["%file"]
[Trace - 1:13:02 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "stdout: \n/Users/tkolleh/**/schema.graphql\n  14:11  warning  Field 'idType' in Type 'Client' uses 'String'. Please use 'ID' instead          relay.id\n  15:13  warning  Field 'idNumber' in Type 'Client' uses 'String'. Please use 'ID' instead        relay.id\n  16:14  warning  Field 'idExpDate' in Type 'Client' uses 'String'. Please use 'ID' instead       relay.id\n  17:19  warning  Field 'idIssuanceDate' in Type 'Client' uses 'String'. Please use 'ID' instead  relay.id\n   1:6   warning  Type 'Client' does not have a description                                       description.type\n  22:6   warning  Type 'EmergencyContact' does not have a description                                                            description.field\n  32:3   warning  Field 'acctNum' does not have a description                                                                       description.field\n\n✖ 56 problems (0 errors, 56 warnings)\n\n"
}

stdout: 
/Users/tkolleh/**/schema.graphql
  14:11  warning  Field 'idType' in Type 'Client' uses 'String'. Please use 'ID' instead          relay.id
  15:13  warning  Field 'idNumber' in Type 'Client' uses 'String'. Please use 'ID' instead        relay.id
  16:14  warning  Field 'idExpDate' in Type 'Client' uses 'String'. Please use 'ID' instead       relay.id
```

**Comment by tkolleh** [comment]
If the issue is with my understanding of the grep command or how the diagnostic-languageserver handles stdout versus stderr, then will close the ticket.

**Comment by iamcco** [comment]
No,  diagnostic-languageserver does not know if it is stdout or stderr, you have to config to tell   
 diagnostic-languageserver to use stdout or stderr or both. By default it use stdout.

**Comment by tkolleh** [comment]
Yes, but from the terminal the command output is *stderr* (see screenshot above) but the diagnostic-languageserver was only able to view it when it was set to *stdout* why is that?

**Comment by iamcco** [comment]
I can't see any screenshot that it's stdout or stderr from above.
