### ISSUE TITLE
Installation error.

### ISSUE THREAD

**Issue by aalexx-S** [iamcco/coc-diagnostic#7]
Hi,
I am having some trouble installing the plugin.
I use ```:CocInstall coc-diagnostic``` and vim reports ```[coc.nvim] Error on load extension coc-diagnostic from /home/[my name]...les/coc-diagnostic/lib/index.js: Error: Cannot find module 'tslib' ```

I am very sure I have tslib installed globally.

I am using Windows10 WSL. Maybe this is the problem?

This is my error log:
2019-09-18T22:05:11.242 ERROR (pid:305) [extensions] - { Error: Cannot find module 'tslib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at req (/home/<user>/.vim/bundle/coc.nvim/build/index.js:48915:21)
    at Object.<anonymous> (/home/<user>/.config/coc/extensions/node_modules/coc-diagnostic/lib/index.js:3:15)
    at Module._compile (/home/<user>/.vim/bundle/coc.nvim/build/index.js:48936:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }

**Comment by iamcco** [comment]
It's weird, please install again. I have publish a new version.

**Comment by aalexx-S** [comment]
Now it reports ```Error: Cannot find module 'diagnostic-languageserver'```.
I guess I need to install ```diagnostic-language``` on my own?

**Comment by iamcco** [comment]
I have no idea, seems it has problem of your coc.nvim to install extension.
